export const PRODUCT_NAME = 'CafePOS'

export * from './access.js'
export * from './inventory.js'
export * from './menu.js'
export * from './kitchen.js'
export * from './money.js'
export * from './order.js'
export * from './outbox.js'
export * from './payment.js'
export * from './receipt.js'
export * from './refund.js'
export * from './report.js'
export * from './shift.js'
export * from './sync-event.js'
export * from './submitted-order.js'
export * from './tax.js'
export * from './totals.js'
